services:
  - type: web
    name: loan-approval-risk-analysis
    env: python
    buildCommand: "pip install -r requirements.txt && cd notebooks && python train_model.py"
    startCommand: "cd backend && python app.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5000
